# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SalesCollector' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SalesCollector
    pod 'AWSAppSync', '~> 3.1.0'
    pod 'AmplifyPlugins/AWSS3StoragePlugin'
    pod 'AWSMobileClient'
    pod 'AmplifyPlugins/AWSAPIPlugin'
    pod 'amplify-tools'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'AWSS3'
    pod 'AWSAuthUI', '~> 2.13.0'            # Optional dependency required to use drop-in UI
    pod 'AWSUserPoolsSignIn', '~> 2.13.0' 
end
